dist: xenial

language: python

addons:
  mariadb: "10.3"
  postgresql: "9.4"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_ENV="django>=2.2,<3.0" DB=sqlite
  - DJANGO_ENV="django>=2.2,<3.0" DB=postgres
  - DJANGO_ENV="django>=2.2,<3.0" DB=mysql
  - DJANGO_ENV="django>=3.0,<3.1" DB=sqlite
  - DJANGO_ENV="django>=3.0,<3.1" DB=postgres
  - DJANGO_ENV="django>=3.0,<3.1" DB=mysql

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_ENV="django>=3.0,<3.1" DB=sqlite
    - python: "3.5"
      env: DJANGO_ENV="django>=3.0,<3.1" DB=postgres
    - python: "3.5"
      env: DJANGO_ENV="django>=3.0,<3.1" DB=mysql

install:
  - if [[ $DB == "mysql" ]]; then sudo apt-get install -qq libmysqlclient-dev && pip install mysqlclient; fi
  - if [[ $DB == "postgres" ]]; then pip install psycopg2; fi
  - pip install pip poetry -U
  - poetry install
  - poetry run pip install --pre -U "$DJANGO_ENV" "django-haystack>=3.0b1"
before_script:
  - mysql -u root -e 'create database machina_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  - psql -c 'create database machina_test;' -U postgres
script:
  - make qa
  - make coverage
after_success:
  - codecov
branches:
  only:
    - master
